import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { RoleGate } from "@/components/auth/RoleGate";
import { AppShell } from "@/components/layout/AppShell";
import { EmptyBlock, LoadingBlock } from "@/components/common/StateBlocks";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useCurrentUser } from "@/hooks/use-session";

export const Route = createFileRoute("/studio/$section")({ component: StudioSection });
function StudioSection(){const {section}=Route.useParams();const {data:user}=useCurrentUser(); if(section==="new") return <RoleGate allowed={["creator"]}><CreatePost/></RoleGate>; const table=section==="posts"?"posts":section==="plans"?"subscription_plans":section==="subscribers"?"subscriptions":section==="finance"?"transactions":"creator_profiles"; const q=useQuery({queryKey:["studio",table,user?.user.id],enabled:Boolean(user?.user.id),queryFn:async()=>{const column=table==="subscription_plans"?"creator_id":table==="subscriptions"?"creator_id":table==="creator_profiles"?"user_id":"creator_id";const {data,error}=await supabase.from(table as any).select("*").eq(column,user!.user.id).order("created_at",{ascending:false}).limit(50);if(error)throw error;return data??[];}}); return <RoleGate allowed={["creator"]}><AppShell title={`Studio · ${section}`}><div className="flex items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold capitalize">{section}</h2><p className="mt-1 text-sm text-muted-foreground">Dados reais do seu espaço de criador.</p></div>{section==="posts"&&<Button asChild><Link to="/studio/$section" params={{section:"new"}}>Nova publicação</Link></Button>}</div><div className="mt-6 surface-card overflow-hidden">{q.isLoading?<LoadingBlock/>:q.error?<EmptyBlock title="Não foi possível carregar" description="Verifique as permissões da conta."/>:q.data?.length===0?<EmptyBlock title="Nada aqui ainda" description="Comece configurando seu perfil e publicando conteúdo."/>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-border text-left text-muted-foreground"><tr><th className="px-4 py-3">ID</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Data</th></tr></thead><tbody>{q.data.map((r:any)=><tr key={r.id} className="border-b border-border/60"><td className="px-4 py-3 font-mono text-xs">{r.id}</td><td className="px-4 py-3">{r.status??r.name??r.title??(r.is_active?"Ativo":"—")}</td><td className="px-4 py-3 text-muted-foreground">{r.created_at?new Date(r.created_at).toLocaleString("pt-BR"):"—"}</td></tr>)}</tbody></table></div>}</div></AppShell></RoleGate>}
function CreatePost(){const {data}=useCurrentUser();const [title,setTitle]=useState("");const [body,setBody]=useState("");const [exclusive,setExclusive]=useState(false);const [saved,setSaved]=useState(false);async function publish(){if(!data?.user.id)return;const {error}=await supabase.from("posts").insert({creator_id:data.user.id,title,body,visibility:exclusive?"subscribers":"public",is_published:true});if(!error)setSaved(true);}return <AppShell title="Nova publicação"><div className="max-w-2xl space-y-4"><Input placeholder="Título" value={title} onChange={e=>setTitle(e.target.value)}/><Textarea placeholder="Escreva para sua comunidade…" className="min-h-48" value={body} onChange={e=>setBody(e.target.value)}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={exclusive} onChange={e=>setExclusive(e.target.checked)}/> Somente assinantes</label><Button onClick={publish}>Publicar</Button>{saved&&<p className="text-sm text-muted-foreground">Publicação criada.</p>}</div></AppShell>}
