import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { BadgeCheck, Heart, Lock } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { LoadingBlock, EmptyBlock } from "@/components/common/StateBlocks";
import { UserAvatar } from "@/components/common/UserAvatar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { formatCents } from "@/lib/brand";

export const Route = createFileRoute("/c/$username")({ component: CreatorPage });
function CreatorPage(){const {username}=Route.useParams();const q=useQuery({queryKey:["creator",username],queryFn:async()=>{const {data,error}=await supabase.from("profiles").select("id,username,display_name,bio,avatar_url,cover_url,creator_profiles(headline,category,about,is_verified,subscription_plans(id,name,description,price_cents,currency,is_active))").eq("username",username).maybeSingle();if(error)throw error;return data;}});if(q.isLoading)return <LoadingBlock/>;if(!q.data)return <AppShell title="Criador"><EmptyBlock title="Criador não encontrado" description="Este perfil não está publicado ou não existe."/></AppShell>;const cp=(q.data as any).creator_profiles?.[0];return <AppShell title={q.data.display_name??"Criador"}><div className="surface-card overflow-hidden"><div className="h-40 bg-brand-gradient opacity-80"/><div className="-mt-10 px-5 pb-6"><UserAvatar name={q.data.display_name} path={q.data.avatar_url} className="size-20 ring-4 ring-card"/><div className="mt-4 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold">{q.data.display_name}</h1>{cp?.is_verified&&<BadgeCheck className="size-5 text-primary"/>}{cp?.category&&<Badge variant="secondary">{cp.category}</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">@{q.data.username}</p><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">{cp?.about??q.data.bio??cp?.headline??"Este criador ainda não adicionou uma descrição."}</p><div className="mt-6 flex flex-wrap gap-3">{cp?.subscription_plans?.filter((p:any)=>p.is_active).map((plan:any)=><div key={plan.id} className="rounded-2xl border border-border bg-secondary/50 p-4 min-w-[220px]"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{plan.name}</p><p className="mt-1 text-xs text-muted-foreground">{plan.description}</p></div><span className="font-semibold text-primary">{formatCents(plan.price_cents,plan.currency)}</span></div><Button asChild className="mt-4 w-full"><Link to="/checkout/$planId" params={{planId:plan.id}}>Assinar</Link></Button></div>)}</div></div></div><div className="mt-7 grid gap-4"><div className="surface-card p-5"><div className="flex items-center gap-2"><Heart className="size-4 text-primary"/><h2 className="font-semibold">Conteúdo</h2></div><div className="mt-5 rounded-2xl border border-border p-6 text-center"><Lock className="mx-auto size-6 text-primary"/><p className="mt-3 text-sm text-muted-foreground">Conteúdos públicos e exclusivos aparecerão aqui conforme o criador publicar.</p></div></div></div></AppShell>}
