/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as CUsernameRouteImport } from './routes/c/$username'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout/$planId'
import { Route as StudioSectionRouteImport } from './routes/studio.$section'
import { Route as StudioMessagesRouteImport } from './routes/studio.messages'
import { Route as SuperAdminSectionRouteImport } from './routes/super-admin.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const CUsernameRoute = CUsernameRouteImport.update({
  id: '/c/$username',
  path: '/c/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSectionRoute = StudioSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMessagesRoute = StudioMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudioRoute,
} as any)
const SuperAdminSectionRoute = SuperAdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/admin': typeof AdminRouteWithChildren
  '/feed': typeof FeedRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/c/$username': typeof CUsernameRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/studio/$section': typeof StudioSectionRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/super-admin/$section': typeof SuperAdminSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/admin': typeof AdminRouteWithChildren
  '/feed': typeof FeedRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/c/$username': typeof CUsernameRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/studio/$section': typeof StudioSectionRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/super-admin/$section': typeof SuperAdminSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRoute
  '/admin': typeof AdminRouteWithChildren
  '/feed': typeof FeedRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/studio': typeof StudioRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/c/$username': typeof CUsernameRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/studio/$section': typeof StudioSectionRoute
  '/studio/messages': typeof StudioMessagesRoute
  '/super-admin/$section': typeof SuperAdminSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/admin'
    | '/feed'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/studio'
    | '/super-admin'
    | '/admin/$section'
    | '/c/$username'
    | '/checkout/$planId'
    | '/studio/$section'
    | '/studio/messages'
    | '/super-admin/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/admin'
    | '/feed'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/studio'
    | '/super-admin'
    | '/admin/$section'
    | '/c/$username'
    | '/checkout/$planId'
    | '/studio/$section'
    | '/studio/messages'
    | '/super-admin/$section'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/admin'
    | '/feed'
    | '/messages'
    | '/profile'
    | '/reset-password'
    | '/studio'
    | '/super-admin'
    | '/admin/$section'
    | '/c/$username'
    | '/checkout/$planId'
    | '/studio/$section'
    | '/studio/messages'
    | '/super-admin/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeedRoute: typeof FeedRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudioRoute: typeof StudioRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  CUsernameRoute: typeof CUsernameRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/c/$username': {
      id: '/c/$username'
      path: '/c/$username'
      fullPath: '/c/$username'
      preLoaderRoute: typeof CUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$section': {
      id: '/studio/$section'
      path: '/$section'
      fullPath: '/studio/$section'
      preLoaderRoute: typeof StudioSectionRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/messages': {
      id: '/studio/messages'
      path: '/messages'
      fullPath: '/studio/messages'
      preLoaderRoute: typeof StudioMessagesRouteImport
      parentRoute: typeof StudioRoute
    }
    '/super-admin/$section': {
      id: '/super-admin/$section'
      path: '/$section'
      fullPath: '/super-admin/$section'
      preLoaderRoute: typeof SuperAdminSectionRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudioRouteChildren {
  StudioSectionRoute: typeof StudioSectionRoute
  StudioMessagesRoute: typeof StudioMessagesRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioSectionRoute: StudioSectionRoute,
  StudioMessagesRoute: StudioMessagesRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminSectionRoute: typeof SuperAdminSectionRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminSectionRoute: SuperAdminSectionRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  AdminRoute: AdminRouteWithChildren,
  FeedRoute: FeedRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudioRoute: StudioRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  CUsernameRoute: CUsernameRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
