import { useQuery } from "@tanstack/react-query";
import { ArrowDownLeft, ArrowUpRight, Clock3 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useCurrentUser } from "@/hooks/use-session";
import { formatCents } from "@/lib/brand";
import { EmptyBlock, LoadingBlock } from "@/components/common/StateBlocks";

export function FinanceHistory(){
 const {data:current}=useCurrentUser();
 const q=useQuery({queryKey:["finance-history",current?.user.id],enabled:Boolean(current?.user.id),queryFn:async()=>{const [s,p]=await Promise.all([supabase.from("subscriptions").select("id,amount_cents,creator_amount_cents,currency,status,created_at,paid_at").eq("creator_id",current!.user.id).order("created_at",{ascending:false}).limit(100),supabase.from("payout_requests").select("id,amount_cents,currency,status,created_at,reviewed_at,rejection_reason").eq("creator_id",current!.user.id).order("created_at",{ascending:false}).limit(100)]);if(s.error)throw s.error;if(p.error)throw p.error;const events=[...(s.data??[]).map((x:any)=>({id:`sub-${x.id}`,kind:"subscription",amount:x.creator_amount_cents??0,currency:x.currency??"USD",status:x.status,date:x.paid_at??x.created_at,label:"Receita de assinatura",positive:true})),...(p.data??[]).map((x:any)=>({id:`payout-${x.id}`,kind:"payout",amount:x.amount_cents??0,currency:x.currency??"USD",status:x.status,date:x.reviewed_at??x.created_at,label:"Solicitação de saque",positive:false,rejection_reason:x.rejection_reason}))];return events.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());}});
 if(q.isLoading)return <LoadingBlock/>;if(q.error)return <EmptyBlock title="Histórico indisponível" description="Não foi possível carregar o histórico financeiro."/>;if(!q.data?.length)return <EmptyBlock title="Nenhuma movimentação" description="Suas receitas e solicitações de saque aparecerão aqui."/>;
 return <div className="surface-card overflow-hidden"><div className="border-b border-border p-5"><h3 className="font-semibold">Histórico financeiro</h3><p className="mt-1 text-xs text-muted-foreground">Receitas e saques registrados pela SECRET.</p></div><div className="divide-y divide-border">{q.data.map((e:any)=><div key={e.id} className="flex items-center gap-3 p-4"><div className="rounded-full bg-secondary p-2">{e.kind==="subscription"?<ArrowDownLeft className="size-4 text-primary"/>:<ArrowUpRight className="size-4"/>}</div><div className="min-w-0 flex-1"><p className="font-medium">{e.label}</p><p className="text-xs text-muted-foreground">{new Date(e.date).toLocaleString("pt-BR")} · {e.status}</p>{e.rejection_reason&&<p className="text-xs text-destructive">{e.rejection_reason}</p>}</div><div className="text-right"><p className="font-semibold">{e.positive?"+":"-"}{formatCents(e.amount,e.currency)}</p>{e.status==="pending"&&<p className="flex items-center justify-end gap-1 text-xs text-muted-foreground"><Clock3 className="size-3"/>Pendente</p>}</div></div>)}</div></div>;
}
